### PR TITLE
Set up

### PR DESCRIPTION
**Pull request by KaskMIL**
# In this new Pull Request I'm adding the initial set-up to start working on the app
- Set the repo as a React App.
- Install GitHub Linters and local linters.

### CODE REVIEW

**Review by brytebee — CHANGES_REQUESTED** [review]
Hi, @KaskMIL👋,

Good job so far coming so far with the progress you've made! 💪💪

## Highlights
You have done amazing in the following:
- You have used the create-react-app to create the project.✔️
- There are no linter errors. All green.✔️
- The app runs as expected and the file structure is as required.✔️
 
However, there are some issues that you still need to work on to go to the next project but you are almost there!



# Required Changes ♻️

- [ ] **Required:** Kindly update your readme file with the [Microverse Template](https://github.com/microverseinc/readme-template). This is to make your project documentation professional always.

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Please, remember to tag me in your question so I can receive the notification.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @brytebee in your question so I can receive the notification.
### _**Use @brytebee on slack for faster responses.**_


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by KaskMIL** [comment]
Hi @KaskMIL,
Thanks for your review, I just update the README file.
Have a great day!
cheers

**Review by ShadyShawkat — APPROVED** [review]
## Hi @KaskMIL, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Image

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by KaskMIL** [comment]
Hi @ShadyShawkat,
Thanks for your review!
Happy coding!

**Pull request merged**
