### PR TITLE
Refactor calculator.js file to use useState

### PR DESCRIPTION
**Pull request by KaskMIL**
# In this new Pull Request I adding the following feature:
- Refactor the calculator.js file to use **useState** on the calculator function.
- Refactor the rest of the code in the calculator function.

### CODE REVIEW

**Review by Gambit142 — CHANGES_REQUESTED** [review]
Hi @KaskMIL 👋, 

Great work breaking the components further and using the map function. 👏  

## Highlights
- Changed all class-based components to functional components. 💯 
- Good use of React hooks 💯 

However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
#### I am making this comment here because I can not highlight the necessary piece of code.

- [ ] I noticed I can not perform mathematical operations that have to do with the _**`dot (.)`**_. In your buttons.js file, kindly adjust the value in the default prop from `,` to `.` 👍 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider

N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

**Comment by KaskMIL** [comment]
Hi @Gambit142,
Thanks for your review, it was a typo problem 🥲 
Cheers

**Review by CollinsTatang — APPROVED** [review]
# Approved 👏  

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
### **Congratulations!** 🎉 
image



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @CollinsTatang in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by KaskMIL** [comment]
Hi @CollinsTatang,
Thanks for your review,
Happy coding!

**Pull request merged**
